/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ToDoApp;

import controller.ProjectController;
import java.util.Calendar;
import model.Project;




public class App {
   
   
   public static void main(String[] args) {
      Calendar cal = Calendar.getInstance();
      ProjectController projectCtrlr = new ProjectController();
      
      Project project = new Project();
      project.setName("Projeto 2");
      project.setDescription("segundo PRojeto ");
      project.setCreatedAt(cal.getTime());
      project.setUpdatedAt(cal.getTime());
      projectCtrlr.save(project);
   }
}
