/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ToDoApp;

import controller.ProjectController;
import java.util.Calendar;
import model.Project;
import view.Home;




public class App {
   
   
   public static void main(String[] args) {
      Home home = new Home();
   }
}
