/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view;

import controller.ProjectController;
import java.util.Calendar;
import javax.swing.JOptionPane;
import model.Project;

/**
 *
 * @author vito
 */
public class ProjectDialogScreen extends javax.swing.JDialog {
   
   
   //codigo adicionado manualmente
   ProjectController controller;

   public ProjectDialogScreen(java.awt.Frame parent, boolean modal) {
      super(parent, modal);
      initComponents();

      controller = new ProjectController();
   }

   /**
    * This method is called from within the constructor to initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is always
    * regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      jPanelToolbar = new javax.swing.JPanel();
      jLabelToolbarTitle = new javax.swing.JLabel();
      jLabelProjectToolbarSave = new javax.swing.JLabel();
      jPanel2 = new javax.swing.JPanel();
      jLabelName = new javax.swing.JLabel();
      jLabelDescription = new javax.swing.JLabel();
      jTextFieldName = new javax.swing.JTextField();
      jScrollPane1 = new javax.swing.JScrollPane();
      jTextAreaDescription = new javax.swing.JTextArea();

      setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

      jPanelToolbar.setBackground(new java.awt.Color(0, 153, 102));

      jLabelToolbarTitle.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
      jLabelToolbarTitle.setForeground(java.awt.Color.white);
      jLabelToolbarTitle.setText("Projeto");

      jLabelProjectToolbarSave.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
      jLabelProjectToolbarSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/check.png"))); // NOI18N
      jLabelProjectToolbarSave.addMouseListener(new java.awt.event.MouseAdapter() {
         public void mouseClicked(java.awt.event.MouseEvent evt) {
            jLabelProjectToolbarSaveMouseClicked(evt);
         }
      });

      javax.swing.GroupLayout jPanelToolbarLayout = new javax.swing.GroupLayout(jPanelToolbar);
      jPanelToolbar.setLayout(jPanelToolbarLayout);
      jPanelToolbarLayout.setHorizontalGroup(
         jPanelToolbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(jPanelToolbarLayout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jLabelToolbarTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGap(18, 18, 18)
            .addComponent(jLabelProjectToolbarSave, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap())
      );
      jPanelToolbarLayout.setVerticalGroup(
         jPanelToolbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelToolbarLayout.createSequentialGroup()
            .addGroup(jPanelToolbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
               .addComponent(jLabelProjectToolbarSave, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE)
               .addComponent(jLabelToolbarTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addContainerGap())
      );

      jPanel2.setBackground(new java.awt.Color(255, 255, 255));

      jLabelName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
      jLabelName.setText("Nome");

      jLabelDescription.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
      jLabelDescription.setText("Descrição");

      jTextFieldName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
      jTextFieldName.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            jTextFieldNameActionPerformed(evt);
         }
      });

      jTextAreaDescription.setColumns(20);
      jTextAreaDescription.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
      jTextAreaDescription.setRows(5);
      jScrollPane1.setViewportView(jTextAreaDescription);

      javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
      jPanel2.setLayout(jPanel2Layout);
      jPanel2Layout.setHorizontalGroup(
         jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(jPanel2Layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addComponent(jLabelDescription, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
               .addComponent(jLabelName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
               .addComponent(jTextFieldName)
               .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE))
            .addContainerGap())
      );
      jPanel2Layout.setVerticalGroup(
         jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(jPanel2Layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jLabelName)
            .addGap(3, 3, 3)
            .addComponent(jTextFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(jLabelDescription)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jScrollPane1)
            .addContainerGap())
      );

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
      getContentPane().setLayout(layout);
      layout.setHorizontalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addComponent(jPanelToolbar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
         .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
      );
      layout.setVerticalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addComponent(jPanelToolbar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
      );

      pack();
   }// </editor-fold>//GEN-END:initComponents

   private void jTextFieldNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNameActionPerformed
      // TODO add your handling code here:
   }//GEN-LAST:event_jTextFieldNameActionPerformed
   
   
   
   //codigo adicionado manualmente
   private void jLabelProjectToolbarSaveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelProjectToolbarSaveMouseClicked
     
      try {
         Project project = new Project();
         Calendar calendar = Calendar.getInstance();
         project.setName(jTextFieldName.getText());
         project.setDescription(jTextAreaDescription.getText());
         project.setCreatedAt(calendar.getTime());
         project.setUpdatedAt(calendar.getTime());
         controller.save(project);
         JOptionPane.showMessageDialog(rootPane, "Projeto salvo com sucesso!");
      } catch (Exception e) {
         JOptionPane.showMessageDialog(rootPane, e.getMessage());
      }
      this.dispose();
   }//GEN-LAST:event_jLabelProjectToolbarSaveMouseClicked

   /**
    * @param args the command line arguments
    */
   public static void main(String args[]) {
      try {
         for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            if ("Java swing".equals(info.getName())) {
               javax.swing.UIManager.setLookAndFeel(info.getClassName());
               break;
            }
         }
      } catch (ClassNotFoundException ex) {
         java.util.logging.Logger.getLogger(ProjectDialogScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (InstantiationException ex) {
         java.util.logging.Logger.getLogger(ProjectDialogScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (IllegalAccessException ex) {
         java.util.logging.Logger.getLogger(ProjectDialogScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (javax.swing.UnsupportedLookAndFeelException ex) {
         java.util.logging.Logger.getLogger(ProjectDialogScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      }
      //</editor-fold>

      /* Create and display the dialog */
      java.awt.EventQueue.invokeLater(new Runnable() {
         public void run() {
            ProjectDialogScreen dialog = new ProjectDialogScreen(new javax.swing.JFrame(), true);
            dialog.addWindowListener(new java.awt.event.WindowAdapter() {
               @Override
               public void windowClosing(java.awt.event.WindowEvent e) {
                  System.exit(0);
               }
            });
            dialog.setVisible(true);
         }
      });
   }

   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JLabel jLabelDescription;
   private javax.swing.JLabel jLabelName;
   private javax.swing.JLabel jLabelProjectToolbarSave;
   private javax.swing.JLabel jLabelToolbarTitle;
   private javax.swing.JPanel jPanel2;
   private javax.swing.JPanel jPanelToolbar;
   private javax.swing.JScrollPane jScrollPane1;
   private javax.swing.JTextArea jTextAreaDescription;
   private javax.swing.JTextField jTextFieldName;
   // End of variables declaration//GEN-END:variables
}
